// USERS
export const USER = {
    LOAD: 'FETCHING_USER',
    LOAD_SUCCESS: 'FETCHED_USER',
    LOAD_FAILURE: 'FETCH_USER_ERROR',
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
}

export const COURSES = {}