// USERS
export const USER = {
    LOAD: 'FETCHING_USER',
    LOAD_SUCCESS: 'FETCHED_USER',
    LOAD_FAILURE: 'FETCH_USER_ERROR',
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOG_OUT: 'LOG_OUT',
}

export const COURSES = {
    LOAD: 'FETCHING_COURSE',
    LOAD_SUCCESS: 'FETCHED_COURSE',
    LOAD_FAILURE: 'FETCH_COURSE_ERROR',
}

export const ATTENDANCE = {
    SELECTED_COURSE: 'SELECTED_COURSE',
    SELECTED_INDEX: 'SELECTED_INDEX',
    SELECTED_DATE: 'SELECTED_DATE',
    FETCH_ATTENDANCE: 'FETCH_ATTENDANCE',
    FETCHED_ATTENDANCE: 'FETCHED_ATTENDANCE',
    FETCH_ATTENDANCE_ERROR: 'FETCH_ATTENDANCE_ERROR',
}

export const ABSENTEE = {
    LOAD: 'FETCHING_ABSENTEE',
    LOAD_SUCCESS: 'FETCHED_ABSENTEE',
    LOAD_FAILURE: 'FETCH_ABSENTEE_ERROR',
}